name: Build Proxy DLL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build DLL
        run: msbuild src/d3d12_proxy.vcxproj /p:Configuration=Release /p:Platform=x64

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: d3d12-proxy-dll
          path: |
            **/Release/x64/d3d12.dll
